name: Metrics

on:
  schedule:
    - cron: "0 2 * * *"   # tous les jours à 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Output
          filename: github-metrics.svg
          output_action: commit
          committer_message: "chore: update metrics"

          # Base
          base: header, activity, repositories

          # Theme (dark)
          config_display: large
          config_padding: 0, 8 + 0%
          config_timezone: Europe/Paris

          # Languages (✅ pourcentages)
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_sections: most-used

          # (Optionnel) si ça pollue tes stats
          # plugin_languages_skipped: html, css
          # plugin_languages_ignored: repo1, repo2
